#############################################################################
# Makefile for building: BudgetControl
# Generated by qmake (3.1) (Qt 6.2.0)
# Project:  BudgetControl.pro
# Template: subdirs
# Command: D:\Qt\6.2.0\mingw81_64\bin\qmake.exe -o Makefile BudgetControl.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\6.2.0\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\6.2.0\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\6.2.0\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-src-main


sub-src-main-qmake_all:  FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro"
	cd src\main\ && $(MAKE) -f Makefile qmake_all
sub-src-main: FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile
sub-src-main-make_first: FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile 
sub-src-main-all: FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile all
sub-src-main-clean: FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile clean
sub-src-main-distclean: FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile distclean
sub-src-main-install_subtargets: FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile install
sub-src-main-uninstall_subtargets: FORCE
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile uninstall

Makefile: BudgetControl.pro D:/Qt/6.2.0/mingw81_64/mkspecs/win32-g++/qmake.conf D:/Qt/6.2.0/mingw81_64/mkspecs/features/spec_pre.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/device_config.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/common/sanitize.conf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/common/gcc-base.conf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/common/g++-base.conf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/common/windows-vulkan.conf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/common/g++-win32.conf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/common/windows-desktop.conf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/qconfig.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/qt_functions.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/qt_config.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/win32-g++/qmake.conf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/spec_post.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/exclusive_builds.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/toolchain.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/default_pre.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/win32/default_pre.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/resolve_config.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/default_post.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/entrypoint.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/precompile_header.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/warn_on.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/qmake_use.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/file_copies.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/win32/windows.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/testcase_targets.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/exceptions.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/yacc.prf \
		D:/Qt/6.2.0/mingw81_64/mkspecs/features/lex.prf \
		BudgetControl.pro
	$(QMAKE) -o Makefile BudgetControl.pro
D:/Qt/6.2.0/mingw81_64/mkspecs/features/spec_pre.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/device_config.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/common/sanitize.conf:
D:/Qt/6.2.0/mingw81_64/mkspecs/common/gcc-base.conf:
D:/Qt/6.2.0/mingw81_64/mkspecs/common/g++-base.conf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/common/windows-vulkan.conf:
D:/Qt/6.2.0/mingw81_64/mkspecs/common/g++-win32.conf:
D:/Qt/6.2.0/mingw81_64/mkspecs/common/windows-desktop.conf:
D:/Qt/6.2.0/mingw81_64/mkspecs/qconfig.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/qt_functions.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/qt_config.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/win32-g++/qmake.conf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/spec_post.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/exclusive_builds.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/toolchain.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/default_pre.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/win32/default_pre.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/resolve_config.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/default_post.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/entrypoint.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/precompile_header.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/warn_on.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/qmake_use.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/file_copies.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/win32/windows.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/testcase_targets.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/exceptions.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/yacc.prf:
D:/Qt/6.2.0/mingw81_64/mkspecs/features/lex.prf:
BudgetControl.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile BudgetControl.pro

qmake_all: sub-src-main-qmake_all FORCE

make_first: sub-src-main-make_first  FORCE
all: sub-src-main-all  FORCE
clean: sub-src-main-clean  FORCE
distclean: sub-src-main-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-src-main-install_subtargets FORCE
uninstall_subtargets: sub-src-main-uninstall_subtargets FORCE

sub-src-main-debug:
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile debug
debug: sub-src-main-debug

sub-src-main-release:
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile release
release: sub-src-main-release

sub-src-main-check:
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile check
check: sub-src-main-check

sub-src-main-benchmark:
	@if not exist src\main\ mkdir src\main\ & if not exist src\main\ exit 1
	cd src\main\ && ( if not exist Makefile $(QMAKE) -o Makefile "D:\mycppach\qt\mdkp\for pacanov\BudgetControl\src\main\main.pro" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-main-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

